package com.example.al_aalim.model

data class Surah(
    val number: Int,
    val name: String,
    val arabicName: String,
    val englishName: String,
    val meaning: String
)

object SurahData {
    fun getAllSurahs(): List<Surah> = listOf(
        Surah(1,   "Al-Fatihah",       "الفاتحة",        "Al-Fatihah",       "The Opening"),
        Surah(2,   "Al-Baqarah",       "البقرة",          "Al-Baqarah",       "The Cow"),
        Surah(3,   "Ali 'Imran",       "آل عمران",        "Ali 'Imran",       "Family of Imran"),
        Surah(4,   "An-Nisa",          "النساء",          "An-Nisa",          "The Women"),
        Surah(5,   "Al-Ma'idah",       "المائدة",         "Al-Ma'idah",       "The Table Spread"),
        Surah(6,   "Al-An'am",         "الأنعام",         "Al-An'am",         "The Cattle"),
        Surah(7,   "Al-A'raf",         "الأعراف",         "Al-A'raf",         "The Heights"),
        Surah(8,   "Al-Anfal",         "الأنفال",         "Al-Anfal",         "The Spoils of War"),
        Surah(9,   "At-Tawbah",        "التوبة",          "At-Tawbah",        "The Repentance"),
        Surah(10,  "Yunus",            "يونس",            "Yunus",            "Jonah"),
        Surah(11,  "Hud",              "هود",             "Hud",              "Hud"),
        Surah(12,  "Yusuf",            "يوسف",            "Yusuf",            "Joseph"),
        Surah(13,  "Ar-Ra'd",          "الرعد",           "Ar-Ra'd",          "The Thunder"),
        Surah(14,  "Ibrahim",          "إبراهيم",         "Ibrahim",          "Abraham"),
        Surah(15,  "Al-Hijr",          "الحجر",           "Al-Hijr",          "The Rocky Tract"),
        Surah(16,  "An-Nahl",          "النحل",           "An-Nahl",          "The Bee"),
        Surah(17,  "Al-Isra",          "الإسراء",         "Al-Isra",          "The Night Journey"),
        Surah(18,  "Al-Kahf",          "الكهف",           "Al-Kahf",          "The Cave"),
        Surah(19,  "Maryam",           "مريم",            "Maryam",           "Mary"),
        Surah(20,  "Ta-Ha",            "طه",              "Ta-Ha",            "Ta-Ha"),
        Surah(21,  "Al-Anbiya",        "الأنبياء",        "Al-Anbiya",        "The Prophets"),
        Surah(22,  "Al-Hajj",          "الحج",            "Al-Hajj",          "The Pilgrimage"),
        Surah(23,  "Al-Mu'minun",      "المؤمنون",        "Al-Mu'minun",      "The Believers"),
        Surah(24,  "An-Nur",           "النور",           "An-Nur",           "The Light"),
        Surah(25,  "Al-Furqan",        "الفرقان",         "Al-Furqan",        "The Criterion"),
        Surah(26,  "Ash-Shu'ara",      "الشعراء",         "Ash-Shu'ara",      "The Poets"),
        Surah(27,  "An-Naml",          "النمل",           "An-Naml",          "The Ant"),
        Surah(28,  "Al-Qasas",         "القصص",           "Al-Qasas",         "The Stories"),
        Surah(29,  "Al-'Ankabut",      "العنكبوت",        "Al-'Ankabut",      "The Spider"),
        Surah(30,  "Ar-Rum",           "الروم",           "Ar-Rum",           "The Romans"),
        Surah(31,  "Luqman",           "لقمان",           "Luqman",           "Luqman"),
        Surah(32,  "As-Sajdah",        "السجدة",          "As-Sajdah",        "The Prostration"),
        Surah(33,  "Al-Ahzab",         "الأحزاب",         "Al-Ahzab",         "The Confederate Tribes"),
        Surah(34,  "Saba",             "سبأ",             "Saba",             "Sheba"),
        Surah(35,  "Fatir",            "فاطر",            "Fatir",            "The Originator"),
        Surah(36,  "Ya-Sin",           "يس",              "Ya-Sin",           "Ya-Sin"),
        Surah(37,  "As-Saffat",        "الصافات",         "As-Saffat",        "Those Drawn Up in Ranks"),
        Surah(38,  "Sad",              "ص",               "Sad",              "Sad"),
        Surah(39,  "Az-Zumar",         "الزمر",           "Az-Zumar",         "The Groups"),
        Surah(40,  "Ghafir",           "غافر",            "Ghafir",           "The Forgiver"),
        Surah(41,  "Fussilat",         "فصلت",            "Fussilat",         "Explained in Detail"),
        Surah(42,  "Ash-Shura",        "الشورى",          "Ash-Shura",        "The Consultation"),
        Surah(43,  "Az-Zukhruf",       "الزخرف",          "Az-Zukhruf",       "The Ornaments of Gold"),
        Surah(44,  "Ad-Dukhan",        "الدخان",          "Ad-Dukhan",        "The Smoke"),
        Surah(45,  "Al-Jathiyah",      "الجاثية",         "Al-Jathiyah",      "The Crouching"),
        Surah(46,  "Al-Ahqaf",         "الأحقاف",         "Al-Ahqaf",         "The Wind-Curved Sandhills"),
        Surah(47,  "Muhammad",         "محمد",            "Muhammad",         "Muhammad"),
        Surah(48,  "Al-Fath",          "الفتح",           "Al-Fath",          "The Victory"),
        Surah(49,  "Al-Hujurat",       "الحجرات",         "Al-Hujurat",       "The Rooms"),
        Surah(50,  "Qaf",              "ق",               "Qaf",              "Qaf"),
        Surah(51,  "Adh-Dhariyat",     "الذاريات",        "Adh-Dhariyat",     "The Winnowing Winds"),
        Surah(52,  "At-Tur",           "الطور",           "At-Tur",           "The Mount"),
        Surah(53,  "An-Najm",          "النجم",           "An-Najm",          "The Star"),
        Surah(54,  "Al-Qamar",         "القمر",           "Al-Qamar",         "The Moon"),
        Surah(55,  "Ar-Rahman",        "الرحمن",          "Ar-Rahman",        "The Beneficent"),
        Surah(56,  "Al-Waqi'ah",       "الواقعة",         "Al-Waqi'ah",       "The Inevitable"),
        Surah(57,  "Al-Hadid",         "الحديد",          "Al-Hadid",         "The Iron"),
        Surah(58,  "Al-Mujadila",      "المجادلة",        "Al-Mujadila",      "The Pleading Woman"),
        Surah(59,  "Al-Hashr",         "الحشر",           "Al-Hashr",         "The Exile"),
        Surah(60,  "Al-Mumtahanah",    "الممتحنة",        "Al-Mumtahanah",    "She That Is Examined"),
        Surah(61,  "As-Saf",           "الصف",            "As-Saf",           "The Ranks"),
        Surah(62,  "Al-Jumu'ah",       "الجمعة",          "Al-Jumu'ah",       "Friday"),
        Surah(63,  "Al-Munafiqun",     "المنافقون",       "Al-Munafiqun",     "The Hypocrites"),
        Surah(64,  "At-Taghabun",      "التغابن",         "At-Taghabun",      "The Mutual Disillusion"),
        Surah(65,  "At-Talaq",         "الطلاق",          "At-Talaq",         "The Divorce"),
        Surah(66,  "At-Tahrim",        "التحريم",         "At-Tahrim",        "The Prohibition"),
        Surah(67,  "Al-Mulk",          "الملك",           "Al-Mulk",          "The Sovereignty"),
        Surah(68,  "Al-Qalam",         "القلم",           "Al-Qalam",         "The Pen"),
        Surah(69,  "Al-Haqqah",        "الحاقة",          "Al-Haqqah",        "The Reality"),
        Surah(70,  "Al-Ma'arij",       "المعارج",         "Al-Ma'arij",       "The Ascending Stairways"),
        Surah(71,  "Nuh",              "نوح",             "Nuh",              "Noah"),
        Surah(72,  "Al-Jinn",          "الجن",            "Al-Jinn",          "The Jinn"),
        Surah(73,  "Al-Muzzammil",     "المزمل",          "Al-Muzzammil",     "The Enshrouded One"),
        Surah(74,  "Al-Muddaththir",   "المدثر",          "Al-Muddaththir",   "The Cloaked One"),
        Surah(75,  "Al-Qiyamah",       "القيامة",         "Al-Qiyamah",       "The Resurrection"),
        Surah(76,  "Al-Insan",         "الإنسان",         "Al-Insan",         "The Man"),
        Surah(77,  "Al-Mursalat",      "المرسلات",        "Al-Mursalat",      "The Emissaries"),
        Surah(78,  "An-Naba",          "النبأ",           "An-Naba",          "The Tidings"),
        Surah(79,  "An-Nazi'at",       "النازعات",        "An-Nazi'at",       "Those Who Drag Forth"),
        Surah(80,  "'Abasa",           "عبس",             "'Abasa",           "He Frowned"),
        Surah(81,  "At-Takwir",        "التكوير",         "At-Takwir",        "The Overthrowing"),
        Surah(82,  "Al-Infitar",       "الانفطار",        "Al-Infitar",       "The Cleaving"),
        Surah(83,  "Al-Mutaffifin",    "المطففين",        "Al-Mutaffifin",    "The Defrauding"),
        Surah(84,  "Al-Inshiqaq",      "الانشقاق",        "Al-Inshiqaq",      "The Splitting Open"),
        Surah(85,  "Al-Buruj",         "البروج",          "Al-Buruj",         "The Mansions of the Stars"),
        Surah(86,  "At-Tariq",         "الطارق",          "At-Tariq",         "The Morning Star"),
        Surah(87,  "Al-A'la",          "الأعلى",          "Al-A'la",          "The Most High"),
        Surah(88,  "Al-Ghashiyah",     "الغاشية",         "Al-Ghashiyah",     "The Overwhelming"),
        Surah(89,  "Al-Fajr",          "الفجر",           "Al-Fajr",          "The Dawn"),
        Surah(90,  "Al-Balad",         "البلد",           "Al-Balad",         "The City"),
        Surah(91,  "Ash-Shams",        "الشمس",           "Ash-Shams",        "The Sun"),
        Surah(92,  "Al-Layl",          "الليل",           "Al-Layl",          "The Night"),
        Surah(93,  "Ad-Duha",          "الضحى",           "Ad-Duha",          "The Morning Hours"),
        Surah(94,  "Ash-Sharh",        "الشرح",           "Ash-Sharh",        "The Relief"),
        Surah(95,  "At-Tin",           "التين",           "At-Tin",           "The Fig"),
        Surah(96,  "Al-'Alaq",         "العلق",           "Al-'Alaq",         "The Clot"),
        Surah(97,  "Al-Qadr",          "القدر",           "Al-Qadr",          "The Power"),
        Surah(98,  "Al-Bayyinah",      "البينة",          "Al-Bayyinah",      "The Clear Proof"),
        Surah(99,  "Az-Zalzalah",      "الزلزلة",         "Az-Zalzalah",      "The Earthquake"),
        Surah(100, "Al-'Adiyat",       "العاديات",        "Al-'Adiyat",       "The Courser"),
        Surah(101, "Al-Qari'ah",       "القارعة",         "Al-Qari'ah",       "The Calamity"),
        Surah(102, "At-Takathur",      "التكاثر",         "At-Takathur",      "The Rivalry in World Increase"),
        Surah(103, "Al-'Asr",          "العصر",           "Al-'Asr",          "The Declining Day"),
        Surah(104, "Al-Humazah",       "الهمزة",          "Al-Humazah",       "The Traducer"),
        Surah(105, "Al-Fil",           "الفيل",           "Al-Fil",           "The Elephant"),
        Surah(106, "Quraysh",          "قريش",            "Quraysh",          "Quraysh"),
        Surah(107, "Al-Ma'un",         "الماعون",         "Al-Ma'un",         "The Small Kindnesses"),
        Surah(108, "Al-Kawthar",       "الكوثر",          "Al-Kawthar",       "The Abundance"),
        Surah(109, "Al-Kafirun",       "الكافرون",        "Al-Kafirun",       "The Disbelievers"),
        Surah(110, "An-Nasr",          "النصر",           "An-Nasr",          "The Divine Support"),
        Surah(111, "Al-Masad",         "المسد",           "Al-Masad",         "The Palm Fiber"),
        Surah(112, "Al-Ikhlas",        "الإخلاص",         "Al-Ikhlas",        "The Sincerity"),
        Surah(113, "Al-Falaq",         "الفلق",           "Al-Falaq",         "The Daybreak"),
        Surah(114, "An-Nas",           "الناس",           "An-Nas",           "The Mankind")
    )
}
